### ISSUE TITLE
Empty Report

### ISSUE THREAD

**Issue by PilotBob** [Rogeriohsjr/CoverageConverter#4]
This task is just what I'm looking for. But, I'm getting an empty summary report. It looks like everything is setup as your sample. The only different I see if we use xUnit. However, I have added the /TestAdapterPath param to the vstest section.

Also, it looks like each run picks up the coverage file from the runs before it. They aren't getting clean out of the pipeline or something. Here's the coverage convertor task log:

2020-06-02T22:01:09.0776752Z ##[section]Starting: Coverage Converter
2020-06-02T22:01:09.0970333Z ==============================================================================
2020-06-02T22:01:09.0970856Z Task         : Coverage Converter
2020-06-02T22:01:09.0971336Z Description  : Convert .coverage file into .coveragexml for use in Code Coverage Report
2020-06-02T22:01:09.0971796Z Version      : 0.1.22
2020-06-02T22:01:09.0972105Z Author       : Rogeriohsjr
2020-06-02T22:01:09.0972428Z Help         : 
2020-06-02T22:01:09.0972823Z ==============================================================================
2020-06-02T22:01:09.5861063Z Starting Code Coverage...
2020-06-02T22:01:09.5863340Z Starting executeVsTestCodeCoverage...
2020-06-02T22:01:14.6260684Z Generating coverage for file [C:\agent\_work\3\s\Amsi.Test\bin\Release\Amsi.Test.dll]
2020-06-02T22:01:35.6004967Z Generating coverage for file [C:\agent\_work\3\s\Amsi.Test\bin\Release\xunit.runner.visualstudio.testadapter.dll]
2020-06-02T22:01:41.4652799Z Ended executeVsTestCodeCoverage...
2020-06-02T22:01:41.4654151Z Starting executeCodeCoverageAnalyze...
2020-06-02T22:01:47.8655090Z Converting this file[C:\agent\_work\3\s\TestResults\12344b20-4210-42dd-8a64-889de8596b29\evolu_USTAWVBUILD3 2020-06-02 17_52_09.coverage] to \TestResults\DynamicCodeCoverage.coveragexml
2020-06-02T22:01:47.8656764Z Converting this file[C:\agent\_work\3\s\TestResults\1422d414-8179-4b6e-b7e9-676d999566cc\evolu_USTAWVBUILD3 2020-06-02 17_31_06.coverage] to \TestResults\DynamicCodeCoverage.coveragexml
2020-06-02T22:01:47.8658482Z Converting this file[C:\agent\_work\3\s\TestResults\94de3efd-d394-4870-bba6-7185a56f3879\evolu_USTAWVBUILD3 2020-06-02 18_01_18.coverage] to \TestResults\DynamicCodeCoverage.coveragexml
2020-06-02T22:01:47.8660196Z Converting this file[C:\agent\_work\3\s\TestResults\9616e109-e0b6-4fff-88da-30d64c6fd851\evolu_USTAWVBUILD3 2020-06-02 18_01_39.coverage] to \TestResults\DynamicCodeCoverage.coveragexml
2020-06-02T22:01:47.8661395Z Converting this file[C:\agent\_work\3\s\TestResults\ab587ac6-2d7e-4707-b341-84630044d22d\evolu_USTAWVBUILD3 2020-06-02 17_31_28.coverage] to \TestResults\DynamicCodeCoverage.coveragexml
2020-06-02T22:01:47.8662449Z Converting this file[C:\agent\_work\3\s\TestResults\efe8f00a-2b89-4551-b8cc-4ece8ab268a6\evolu_USTAWVBUILD3 2020-06-02 17_52_31.coverage] to \TestResults\DynamicCodeCoverage.coveragexml
2020-06-02T22:01:47.8665588Z Converting All these files["C:\agent\_work\3\s\TestResults\12344b20-4210-42dd-8a64-889de8596b29\evolu_USTAWVBUILD3 2020-06-02 17_52_09.coverage" "C:\agent\_work\3\s\TestResults\1422d414-8179-4b6e-b7e9-676d999566cc\evolu_USTAWVBUILD3 2020-06-02 17_31_06.coverage" "C:\agent\_work\3\s\TestResults\94de3efd-d394-4870-bba6-7185a56f3879\evolu_USTAWVBUILD3 2020-06-02 18_01_18.coverage" "C:\agent\_work\3\s\TestResults\9616e109-e0b6-4fff-88da-30d64c6fd851\evolu_USTAWVBUILD3 2020-06-02 18_01_39.coverage" "C:\agent\_work\3\s\TestResults\ab587ac6-2d7e-4707-b341-84630044d22d\evolu_USTAWVBUILD3 2020-06-02 17_31_28.coverage" "C:\agent\_work\3\s\TestResults\efe8f00a-2b89-4551-b8cc-4ece8ab268a6\evolu_USTAWVBUILD3 2020-06-02 17_52_31.coverage"] to \TestResults\DynamicCodeCoverage.coveragexml
2020-06-02T22:01:47.8858116Z Ended executeCodeCoverageAnalyze...
2020-06-02T22:01:47.8859585Z Ended Code Coverage.
2020-06-02T22:01:47.9551547Z stdout: 
2020-06-02T22:01:47.9552208Z stderr: 
2020-06-02T22:01:47.9697714Z ##[section]Finishing: Coverage Converter

Any suggestions?

**Comment by PilotBob** [comment]
Also... should Test Files in the VS Test task, match the Test files in the code coverage path? Seems like they should, but in your example they are different.

**Comment by Rogeriohsjr** [comment]
Hey @PilotBob  , here are some thoughts:

1. Make sure you have disabled the codeCoverageEnabled: false in VSTest@2
VSTest should run the unit test but should not run the test coverage.

2. Regards this question below:
"should Test Files in the VS Test task, match the Test files in the code coverage path? Seems like they should, but in your example they are different."

I believe you are talking about VSTest@2 testAssemblyVer2 and CoverageConverter@0 listTestFiles, right?

task: VSTest@2
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**

task: CoverageConverter@0
    listTestFiles: '**\bin\**\*.Tests*.dll'

They are not identical, but they do the same thing. They both get the Unit Test Project that I want. In my case my project name was TestWebAppProjA.Tests.dll.


3. You also mention "it looks like each run picks up the coverage file from the runs before it."
When you see the log which starts with "Converting this file", it means that we will convert these files, but we didn't convert that yet.
Then on log "Converting All these files" is the part that join all the files and generate one .coveragexml.
You can look for the logs in this file:
https://github.com/Rogeriohsjr/AzureDevOpsTask/blob/4e8c89202fb4722a89f9430fe58048d435a94225/buildAndReleaseTask/index.ts#L62

4. When you said the tests were empty, did you check the xml that the task added into \TestResults folder or you checked in the azure devops > coverage tab?

5. Do you mind share your yml azure file?

6. I guess you can filter more your test to get your project specific dll, since it seems that you have only one Test Project, change the configuration in CoverageConverter to get your test file.

- task: CoverageConverter@0
  inputs:
    searchFolderForTestFiles: '$(System.DefaultWorkingDirectory)'
    vsTestExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
    vsTestArgs: '/EnableCodeCoverage'
    listTestFiles: '**\bin\**\Amsi.Test.dll'
    searchFolderForCodeCoverageFile: '$(System.DefaultWorkingDirectory)'
    temporaryFolderForCodeCoverage: 'Agent.TempDirectory'
    temporaryFileCoveragexml: '\TestResults\DynamicCodeCoverage.coveragexml'
    codeCoverageArgs: 'analyze /output:'
    codeCoverageExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe'

I hope that helps.

**Comment by PilotBob** [comment]
1. Yes.. disabled. 
2. ok
3. Yes... it's listing multiple coverage files. There should only be 1 coverage file.
4. Yes, in the coverage tab it shows a report with all 0's in it. 
5. I don't use YAML pipelines, still legacy... but here are the tasks in question when I click show YAML in the pipeline editor:

```yaml
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'
  inputs:
    versionSelector: latestStable

- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    vsTestVersion: toolsInstaller
    runTestsInIsolation: true
    codeCoverageEnabled: false
    publishRunAttachments: false

- task: rogeriohsjr.build-release-task.custom-build-release-task.CoverageConverter@0
  displayName: 'Coverage Converter'
  inputs:
    vsTestExeFileLocation: '$(Agent.ToolsDirectory)\VsTest\16.6.1\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'
    vsTestArgs: '/EnableCodeCoverage /TestAdapterPath:"$(Build.SourcesDirectory)"'
    listTestFiles: '**\bin\**\*.tests*.dll'
    codeCoverageExeFileLocation: '$(Agent.ToolsDirectory)\VsTest\16.6.1\x64\tools\net451\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe'

- powershell: |
   # Write your PowerShell commands here.
   
   Write-Host "Convert to XML"
   Write-Host "Tools Directory: $env:Agent_ToolsDirectory"
   Write-Host "Work Directory: $env:Agent_BuildDirectory"
   Write-Host "Temp Directory: $env:Agent_TempDirectory"
   
   $covFile = Get-ChildItem -Path $env:Agent_TempDirectory\TestResults -Recurse -Include "*.coverage" | sort LastWriteTime | select -last 1
   $covFile
   $covFile.FullName
   
   $args = "analyze /output:""$env:Agent_TempDirectory\TestResults\DynamicCodeCoverage.coveragexml"" ""$covFile"""
   Write-Host "Argument List: $args" 
   
   Start-Process "$env:AGENT_TOOLSDIRECTORY\VsTest\16.6.1\x64\tools\net451\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe" -ArgumentList $args -Wait
   
  displayName: 'PowerShell Script'
  enabled: false

- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: ReportGenerator
  inputs:
    reports: '$(Agent.TempDirectory)\TestResults\DynamicCodeCoverage.coveragexml'
    targetdir: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\Cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports'

```
The PowerShell script is disabled. However, if I enable that, disable coverage convertor, re-enable code coverage on the VSTest task... I do get the correct report uploaded with artifacts. It just doesn't show in code coverage tab because as you say in your docs, the VSTask publishes just the .coverage file there.

I also don't know why the YAML doesn't show all the settings that the UI shows:

![image](https://user-images.githubusercontent.com/168663/83649955-cc987b80-a585-11ea-98cb-de7db417ba6d.png)

Also, I had a question about Temp Code Coverate File Location... you show it as Agent.TempDirectory is that correct. It shouldn't be $(Agent.TempDirectory)  ???

Thanks.
